name: Build DNSCloak tipa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Build
        run: |
          make THEOS=~/theos

      - name: Package .tipa
        run: |
          mkdir -p Payload
          cp -r obj/DNSCloak.app Payload/
          zip -r DNSCloak.tipa Payload

      - uses: actions/upload-artifact@v2
        with:
          name: DNSCloak.tipa
          path: DNSCloak.tipa
